"""empty message

Revision ID: 785d74c1029c
Revises: 
Create Date: 2022-05-28 17:46:15.339272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785d74c1029c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('datas', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
